const images = {
  imageTopic1: require('./img_topic_1.png'),
  imageTopic2: require('./img_topic_2.png'),
  imageTopic3: require('./img_topic_3.png'),
  imageTopic4: require('./img_topic_4.png'),
  imageTopic5: require('./img_topic_5.png'),
  imageTopic6: require('./img_topic_6.png'),
  imageTopic7: require('./img_topic_7.png'),
  imageTopic8: require('./img_topic_8.png'),
  imagePost1: require('./img_post_1.png'),
  imagePost2: require('./img_post_2.png'),
  imagePost3: require('./img_post_3.png'),
  imagePost4: require('./img_post_4.png'),
  imagePost5: require('./img_post_5.png'),
  imageAvatar: require('./img_avatar.png'),
  imageAvatar2: require('./img_avatar_2.png'),
  imageAvatar3: require('./img_avatar_3.png'),
  imageAvatar4: require('./img_avatar_4.png'),
  imageAvatar5: require('./img_avatar_5.png'),
  imageAvatar6: require('./img_avatar_6.png'),
  imageProduct: require('./img_product.png'),
  imageCourse: require('./img_course.png'),
  imageExpert: require('./img_expert.jpg'),
  imageTopicOther: require('./img_topic_other.jpg'),
};

export default images;
